# Colors used for mapping Missouri County map
#colors = ["Red", "Green", "Blue", "White", "Black", "Magenta", "Cyan", "Orange"]
colors = ["Red", "Green", "Blue", "White"]

# A Missouri County Data as Graph Dictionary. initialized with County and its neighbours. 
graph = {
    "Atchison": ["Holt", "Nodaway"],
    "Nodaway": ["Atchison", "Holt", "Andrew", "Gentry", "Worth"],
    "Worth": ["Nodaway","Gentry","Harrison"], 
    "Harrison": ["Worth","Gentry","Daviess","Grundy","Mercer"], 
    "Mercer": ["Harrison","Grundy", "Sullivan","Putnam"],
    "Putnam": ["Mercer","Sullivan", "Adair", "Schuyler"],
    "Schuyler": ["Putnam","Adair", "Scotland"],
    "Scotland": ["Schuyler","Adair","Knox","Clark"],
    "Clark": ["Scotland", "Knox", "Lewis"],
    "Holt": ["Atchison", "Andrew","Nodaway"],
    "Andrew": ["Holt", "Buchanan","DeKalb","Gentry","Nodaway"], 
    "Gentry": ["Nodaway","Andrew","DeKalb","Daviess","Harrison","Worth"],
    "Daviess": ["Gentry", "DeKalb", "Caldwell", "Livingston", "Grundy", "Harrison"],
    "Grundy": ["Harrison", "Daviess", "Livingston", "Linn","Sullivan", "Mercer"],
    "Sullivan": ["Mercer", "Grundy","Linn", "Macon", "Adair", "Putnam"],
    "Adair": ["Putnam", "Sullivan", "Linn", "Macon", "Knox", "Scotland","Schuyler"],
    "Knox": ["Adair", "Macon", "Shelby", "Lewis", "Clark", "Scotland"],
    "Lewis": ["Knox", "Shelby", "Marion", "Clark"],
    "Buchanan": ["Platte", "Clinton", "DeKalb", "Andrew"], 
    "DeKalb": ["Andrew", "Buchanan", "Clinton",  "Caldwell",  "Daviess", "Gentry"], 
    "Clinton": ["Buchanan", "Platte",  "Clay", "Ray", "Caldwell", "DeKalb"], 
    "Caldwell": ["DeKalb","Clinton", "Ray", "Carroll", "Livingston", "Daviess"],
    "Livingston": ["Daviess","Caldwell", "Carroll", "Chariton", "Linn", "Grundy"], 
    "Linn": ["Grundy", "Livingston", "Chariton", "Macon", "Adair", "Sullivan"], 
    "Macon": ["Sullivan", "Linn", "Chariton", "Randolph", "Monroe", "Shelby", "Knox", "Adair"], 
    "Shelby": ["Macon", "Randolph", "Monroe", "Marion", "Lewis", "Knox"],
    "Marion": ["Shelby", "Monroe", "Ralls", "Lewis"], 
    "Platte": ["Buchanan", "Clay", "Clinton"],
    "Clay": ["Platte", "Jackson", "Ray", "Clinton"], 
    "Ray": ["Clinton", "Clay",  "Jackson", "Lafayette", "Carroll", "Caldwell"],
    "Carroll": ["Caldwell", "Ray", "Lafayette", "Saline", "Chariton", "Livingston"], 
    "Chariton": ["Livingston", "Carroll", "Saline", "Howard", "Randolph", "Macon", "Linn"],
    "Randolph": ["Chariton", "Howard", "Boone", "Audrain", "Monroe", "Shelby", "Macon"], 
    "Monroe": ["Macon", "Randolph", "Audrain", "Ralls", "Marion", "Shelby"],
    "Ralls": ["Monroe", "Audrain", "Pike","Marion"], 
    "Jackson": ["Cass", "Johnson", "Lafayette",  "Ray", "Clay"],
    "Lafayette": ["Jackson", "Johnson", "Pettis", "Saline", "Carroll", "Ray"],
    "Saline": ["Lafayette", "Pettis", "Cooper", "Howard", "Chariton", "Carroll"],
    "Howard": ["Saline", "Cooper", "Boone", "Randolph", "Chariton"],
    "Boone": ["Howard", "Cooper", "Moniteau", "Cole", "Callaway", "Audrain", "Randolph"],
    "Audrain": ["Randolph", "Boone", "Callaway", "Montgomery", "Pike", "Ralls", "Monroe" ],
    "Pike": ["Audrain", "Montgomery", "Lincoln", "Ralls"], 
    "Cass": [ "Bates", "Henry", "Johnson", "Jackson"], 
    "Johnson": ["Jackson", "Cass", "Henry", "Pettis", "Lafayette"], 
    "Pettis": ["Lafayette", "Johnson", "Henry", "Benton", "Morgan", "Cooper", "Saline"],
    "Cooper": ["Saline", "Pettis","Morgan", "Moniteau", "Boone", "Howard"],
    "Callaway": ["Boone", "Cole", "Osage", "Montgomery","Audrain"], 
    "Montgomery": ["Audrain", "Callaway", "Osage", "Gasconade", "Warren", "Lincoln", "Pike"],
    "Warren": ["Montgomery","Gasconade", "Franklin", "Saint Charles", "Lincoln"],
    "Lincoln": ["Montgomery", "Warren", "Saint Charles", "Pike"], 
    "Saint Charles": ["Warren", "Franklin", "Saint Louis", "Lincoln"], 
    "Bates": ["Vernon", "Saint Clair", "Henry", "Cass" ],
    "Henry": ["Cass", "Bates", "Saint Clair", "Benton", "Pettis", "Johnson"],
    "Benton": ["Henry", "Saint Clair", "Hickory", "Camden", "Morgan","Pettis"],
    "Morgan": ["Pettis", "Benton", "Camden", "Miller", "Moniteau", "Cooper"],
    "Moniteau": ["Cooper", "Morgan", "Miller", "Cole", "Boone"],
    "Cole": ["Moniteau", "Miller", "Osage", "Callaway", "Boone"],  
    "Osage": ["Cole", "Miller", "Maries", "Gasconade", "Montgomery","Callaway"],
    "Gasconade": ["Osage", "Maries", "Phelps", "Crawford", "Franklin","Warren", "Montgomery"], 
    "Franklin": ["Gasconade", "Crawford", "Washington", "Jefferson", "Saint Louis", "Saint Charles", "Warren"], 
    "Saint Louis": ["Franklin", "Jefferson", "Saint Louis city", "Saint Charles"],
    "Saint Louis city": ["Saint Louis"],
    "Jefferson": ["Saint Louis", "Franklin", "Washington", "Saint Francois", "Sainte Genevieve"],
    "Vernon": ["Barton", "Cedar", "Saint Clair", "Bates"], 
    "Saint Clair": ["Bates", "Vernon", "Cedar", "Polk", "Hickory", "Benton", "Henry"],
    "Hickory": ["Saint Clair",  "Polk", "Dallas", "Camden", "Benton"],
    "Camden": ["Benton","Hickory", "Dallas", "Laclede", "Pulaski", "Miller", "Morgan"],
    "Miller": ["Morgan", "Camden", "Pulaski","Maries", "Osage", "Cole", "Moniteau"], 
    "Maries": ["Miller", "Pulaski", "Phelps", "Gasconade", "Osage"],
    "Cedar": [ "Vernon", "Barton", "Dade", "Polk", "Saint Clair"], 
    "Polk": ["Cedar", "Dade", "Greene", "Dallas", "Hickory", "Saint Clair"], 
    "Dallas": ["Hickory", "Polk", "Greene", "Webster", "Laclede", "Camden"],
    "Laclede": ["Dallas", "Webster", "Wright", "Texas", "Pulaski", "Camden"],
    "Pulaski": ["Camden", "Laclede", "Texas", "Phelps", "Maries", "Miller"], 
    "Phelps": ["Pulaski", "Texas", "Dent", "Crawford", "Gasconade", "Maries"],
    "Crawford": ["Gasconade", "Phelps", "Dent", "Iron", "Washington","Franklin"], 
    "Washington": ["Crawford", "Iron", "Saint Francois", "Jefferson","Franklin"],
    "Saint Francois": ["Washington", "Iron", "Madison", "Perry", "Sainte Genevieve", "Jefferson"],
    "Sainte Genevieve": ["Saint Francois", "Perry"], 
    "Perry": ["Sainte Genevieve", "Saint Francois", "Madison", "Bollinger", "Cape Girardeau"],
    "Barton": ["Jasper", "Dade", "Cedar", "Vernon"], 
    "Dade": ["Barton", "Jasper", "Lawrence", "Greene", "Polk", "Cedar"],
    "Jasper": ["Newton", "Lawrence", "Dade", "Barton"], 
    "Lawrence": ["Jasper", "Newton", "Barry", "Stone", "Christian","Greene", "Dade"],
    "Greene": ["Dade", "Lawrence", "Christian", "Webster", "Dallas","Polk"],
    "Webster": ["Greene", "Christian", "Douglas", "Wright", "Laclede", "Dallas"],
    "Wright": ["Webster", "Douglas", "Texas", "Laclede"],
    "Texas": ["Laclede", "Wright","Douglas", "Howell", "Shannon", "Dent" "Phelps", "Pulaski"], 
    "Dent": ["Phelps","Texas", "Shannon", "Reynolds", "Iron" "Crawford"],
    "Reynolds": ["Dent", "Shannon", "Carter", "Wayne", "Iron"], 
    "Iron": ["Crawford","Dent", "Reynolds", "Wayne", "Madison","Saint Francois", "Washington"],
    "Madison": ["Iron", "Wayne", "Bollinger", "Perry", "Saint Francois"],
    "Bollinger": ["Madison", "Wayne", "Stoddard", "Cape Girardeau","Perry"],
    "Cape Girardeau": ["Perry", "Bollinger", "Stoddard", "Scott"], 
    "Newton": ["McDonald", "Barry", "Lawrence", "Jasper"],
    "McDonald": ["Barry", "Newton"], 
    "Barry": ["McDonald", "Stone", "Lawrence", "Newton"],
    "Stone": ["Barry", "Taney", "Christian", "Lawrence"],
    "Christian": ["Lawrence", "Stone", "Taney", "Douglas","Webster", "Greene"],
    "Taney": ["Stone", "Ozark", "Douglas", "Christian"], 
    "Douglas": ["Christian", "Taney", "Ozark", "Howell", "Texas","Wright", "Webster"],
    "Ozark": ["Taney", "Howell", "Douglas"], 
    "Howell": ["Douglas", "Ozark", "Oregon", "Shannon", "Texas"], 
    "Shannon": ["Texas", "Howell", "Oregon", "Carter", "Reynolds", "Dent"], 
    "Oregon": ["Howell", "Ripley", "Carter", "Shannon"],
    "Carter": ["Shannon","Oregon", "Ripley", "Butler", "Wayne" "Reynolds"], 
    "Ripley": ["Oregon", "Butler", "Carter"], 
    "Wayne": [ "Reynolds", "Carter", "Butler", "Stoddard", "Bollinger", "Madison", "Iron"],
    "Butler": ["Ripley", "Dunklin", "Stoddard", "Wayne", "Carter"], 
    "Stoddard": ["Wayne", "Butler", "Dunklin", "New Madrid", "Scott", "Cape Girardeau", "Bollinger"], 
    "Scott": ["Cape Girardeau", "Stoddard", "New Madrid", "Mississippi"],
    "New Madrid": ["Stoddard","Dunklin", "Pemiscot", "Mississippi","Scott"], 
    "Mississippi": ["Scott", "New Madrid"],
    "Dunklin": ["Butler", "Pemiscot", "New Madrid", "Stoddard"], 
    "Pemiscot": ["Dunklin", "New Madrid"]
}